[package]
name = "astar"
version = "0.1.0"
authors = ["khamutov <khamutov@ailabs.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "0.4.0-alpha5"
rand = "*"
lyon = "0.16"